version = 0.1

[default.global.parameters]
stack_name = "ravenloft-winter"

[default.deploy.parameters]
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
