import type { CampaignDefinition, KingdomState } from "./types.js";

export const INITIAL_STATE: KingdomState = {
  provisions: 6,
  militaryStrength: 5,
  unity: 5,
  publicOrder: 6,
  enemyKnowledge: 0,
  undeadAdvance: 1,
};

export const campaign: CampaignDefinition = {
  id: "winter-dead",
  title: "Ravenloft: O Inverno dos Mortos",
  activeTurnId: 1,
  introduction: [
    "Durante quase trezentos anos, o Reino de Valdren sobreviveu cercado pelas Brumas.",
    "Ao norte, montanhas cobertas de neve protegiam o reino das terras selvagens. Ao sul, navios navegavam por uma costa estreita antes de encontrarem a mesma parede branca e silenciosa. Estradas que entravam profundamente nas Brumas podiam retornar ao ponto de partida, desaparecer por semanas ou levar viajantes a lugares que não existiam em nenhum mapa.",
    "Os habitantes de Valdren aprenderam a não questionar as fronteiras do mundo.",
    "As Brumas estavam ali antes deles e provavelmente continuariam ali depois que todos estivessem mortos.",
    "Por gerações, o maior perigo de Valdren não foi sobrenatural.",
    "Foram as guerras entre nobres, as colheitas ruins, os invernos rigorosos, os impostos da Coroa e as antigas disputas entre as Grandes Casas. O reino cresceu fragmentado, sustentado por alianças frágeis e pela certeza de que nenhuma Casa conseguiria sobreviver sozinha.",
    "Então o rei morreu.",
    "O rei Edric III faleceu durante o último verão, depois de uma doença breve. Seu único filho, o príncipe Alaric, tem apenas nove anos. Até que alcance a idade necessária para assumir a Coroa, Valdren é governada pelo Conselho do Trono, formado pelas Casas e instituições mais poderosas do reino.",
    "A princípio, a transição aconteceu sem guerra.",
    "A Casa Valerius assumiu a regência. A Casa Vargen permaneceu responsável pela fronteira norte. A Casa Auremont garantiu o abastecimento das cidades. A Guilda do Ferro Negro continuou armando os soldados. A Ordem do Sino Pálido pediu calma à população. A Irmandade dos Corvos manteve as mensagens circulando entre regiões cada vez mais desconfiadas.",
    "Então chegaram as primeiras notícias do Norte.",
    "Uma aldeia desapareceu.",
    "Depois, uma patrulha não retornou.",
    "Uma fortaleza enviou uma mensagem afirmando que homens mortos estavam caminhando pela neve.",
    "O Conselho considerou os relatos exagerados.",
    "Os lordes do sul acreditaram que a Casa Vargen estava tentando obter mais tropas. Mercadores afirmaram que os refugiados inventavam histórias para receber abrigo. Sacerdotes disseram que o medo estava transformando bandidos em monstros nas histórias populares.",
    "Quando a Fortaleza de Varn deixou de responder, ninguém enviou um exército.",
    "Agora o inverno chegou três meses antes do esperado.",
    "A neve já cobre estradas que deveriam permanecer abertas até o fim do outono. Rios começaram a congelar durante a noite. Corvos enviados ao norte retornam com penas brancas e mensagens que ninguém escreveu.",
    "E milhares de pessoas caminham em direção ao sul.",
    "Atrás delas vem um exército.",
    "Não é um exército de invasores.",
    "É um exército de mortos.",
    "Eles marcham sob os estandartes das fortalezas que destruíram. Entre eles estão soldados desaparecidos, camponeses enterrados durante o último inverno e guerreiros que morreram muitas gerações atrás.",
    "No comando está uma figura que os sobreviventes chamam de Rei Pálido.",
    "Ninguém sabe seu verdadeiro nome.",
    "Alguns dizem que ele é um antigo rei do Norte que retornou para reclamar Valdren.",
    "Outros afirmam que é um feiticeiro vindo de além das Brumas.",
    "Os poucos estudiosos que compreendem a natureza da criatura usam uma palavra mais antiga:",
    "Lich.",
    "Seu exército cresce a cada batalha. Os soldados que morrem enfrentando os mortos levantam-se novamente antes do amanhecer.",
    "E algo ainda mais impossível está acontecendo.",
    "O poder do Rei Pálido parece atravessar as Brumas.",
    "Criaturas de terras desconhecidas surgem entre suas fileiras. Cadáveres usam moedas, armaduras e símbolos que nunca foram vistos em Valdren. Alguns mortos falam línguas que nenhum sábio consegue identificar.",
    "O Conselho ainda não sabe quem é o inimigo.",
    "Não sabe de onde ele veio.",
    "Não sabe onde está seu filactério.",
    "E não sabe por que ele escolheu Valdren.",
    "Sabe apenas que o Norte está caindo.",
    "E que, se as Grandes Casas não agirem juntas, cada soldado perdido tornará o inimigo ainda mais forte.",
  ].join("\n\n"),
  initialState: INITIAL_STATE,
};
