import type { HouseDefinition, HouseId } from "./types.js";

export const houses: Record<HouseId, HouseDefinition> = {
  vargen: {
    id: "vargen",
    name: "Casa Vargen",
    subtitle: "Os Lobos do Norte",
    motto: "Primeiro a muralha. Depois o homem.",
    leaderName: "Lady Elira Vargen",
    publicIntroduction: [
      "A Casa Vargen governa as Marcas do Norte há mais de duzentos anos.",
      "Seus soldados defendem as passagens das montanhas, protegem aldeias isoladas e mantêm as fortalezas que separam o coração de Valdren das terras selvagens.",
      "Os Vargen não são a Casa mais rica nem a mais influente. Seus castelos são austeros, seus campos produzem pouco e seus exércitos dependem dos alimentos enviados pela Casa Auremont.",
      "Entretanto, nenhuma outra Casa conhece melhor as estradas, as montanhas e os perigos do Norte.",
      "O símbolo da Casa é um lobo cinzento diante de uma montanha branca.",
    ].join("\n\n"),
    strength: "Exército experiente, fortalezas e conhecimento do terreno.",
    weakness: "Poucos alimentos, pouca riqueza e tropas já desgastadas.",
    publicInterest: "Impedir que o Norte seja abandonado.",
    privateIntroduction: [
      "Você é Lady Elira Vargen.",
      "Durante dois meses, enviou mensagens ao Conselho alertando sobre desaparecimentos no Norte.",
      "Nenhuma resposta veio.",
      "Quando a aldeia de Hollen foi encontrada vazia, você pediu cinquenta soldados. A Coroa enviou cinco investigadores.",
      "Quando uma patrulha encontrou cadáveres caminhando na neve, você pediu autorização para convocar seus estandartes. A Casa Auremont recusou-se a fornecer provisões para uma mobilização baseada em rumores.",
      "Quando Varn enviou sua última mensagem, você pediu que o reino evacuasse as aldeias próximas.",
      "A Casa Valerius ordenou que a população permanecesse onde estava para evitar pânico.",
      "Agora Varn caiu.",
      "Um dos sobreviventes que chegou à sua fortaleza é seu sobrinho, Arlen Vargen. Ele comandava vinte homens na muralha oeste.",
      "Arlen afirma que os mortos não atacaram imediatamente.",
      "Eles cercaram a fortaleza e permaneceram imóveis durante três noites.",
      "Na quarta noite, o portão principal foi aberto por dentro.",
      "Arlen não sabe quem o abriu.",
      "Ele afirma que alguns soldados ouviram vozes de parentes mortos chamando por eles do lado de fora da muralha.",
      "Antes de fugir, Arlen viu uma figura montada em um cavalo morto, observando a fortaleza de uma colina.",
      "A figura não carregava uma espada.",
      "Carregava a coroa do antigo rei Halric V, desaparecida de seu túmulo há quase cento e cinquenta anos.",
      "Você não sabe se o Rei Pálido é Halric.",
      "Mas sabe que alguém abriu o túmulo real.",
    ].join("\n\n"),
    privateObjective:
      "Preservar pelo menos duas fortalezas do Norte até o fim da campanha.",
    privateConcern:
      "Caso as outras Casas recuem cedo demais, todo o Norte será transformado em parte do exército inimigo.",
  },

  auremont: {
    id: "auremont",
    name: "Casa Auremont",
    subtitle: "Os Senhores da Colheita",
    motto: "Tudo vive da terra.",
    leaderName: "Lorde Marius Auremont",
    publicIntroduction: [
      "A Casa Auremont controla as terras mais produtivas de Valdren.",
      "Seus campos alimentam a capital, suas caravanas abastecem os exércitos e seus celeiros determinam quanto tempo o reino pode resistir durante um cerco.",
      "Os Auremont são conhecidos por evitar guerras sempre que possível. Sua influência vem do controle de recursos, não de grandes exércitos.",
      "Muitos nobres acusam a Casa de usar a fome como instrumento político.",
      "Os Auremont respondem que homens armados ainda precisam comer.",
      "O símbolo da Casa é um veado dourado sobre um campo verde.",
    ].join("\n\n"),
    strength: "Alimentos, riqueza agrícola e influência entre a população rural.",
    weakness: "Território amplo, pouca proteção e dependência de estradas seguras.",
    publicInterest: "Evitar que a guerra provoque fome em todo o reino.",
    privateIntroduction: [
      "Você é Lorde Marius Auremont.",
      "Os relatórios públicos dizem que Valdren possui alimentos suficientes para atravessar o inverno.",
      "Isso não é verdade.",
      "A última colheita foi menor do que o esperado. Uma doença atingiu parte dos rebanhos e três celeiros foram destruídos por incêndios cuja origem ainda não foi explicada.",
      "Se o reino mantiver o consumo atual, as reservas durarão aproximadamente quatro meses.",
      "Se receber dezenas de milhares de refugiados, durarão menos de dois.",
      "Você ocultou esses números porque sabe o que acontecerá quando a população descobrir.",
      "Mercadores esconderão alimentos.",
      "Nobres aumentarão seus estoques particulares.",
      "A população saqueará celeiros antes que a fome realmente comece.",
      "Existe outro problema.",
      "Uma caravana enviada à Fortaleza de Varn retornou sem os condutores. Os cavalos chegaram sozinhos, puxando carroças vazias.",
      "Dentro de uma delas, seus homens encontraram sacos de grãos cobertos de gelo.",
      "Os grãos estavam quentes.",
      "Durante a noite, raízes negras começaram a crescer de dentro dos sacos.",
      "Você ordenou que tudo fosse queimado.",
      "Na manhã seguinte, um de seus administradores desapareceu.",
    ].join("\n\n"),
    privateObjective: "Impedir que Provisões chegue a zero.",
    privateConcern:
      "O inverno pode não estar apenas destruindo os alimentos. Pode estar transformando-os.",
  },

  valerius: {
    id: "valerius",
    name: "Casa Valerius",
    subtitle: "O Sangue da Coroa",
    motto: "O reino acima da Casa.",
    leaderName: "Lady Celene Valerius",
    publicIntroduction: [
      "A Casa Valerius possui laços antigos com a família real.",
      "Seus membros serviram como regentes, conselheiros, comandantes e diplomatas durante gerações. Depois da morte do rei Edric III, foi a Casa Valerius que assumiu a responsabilidade de proteger o príncipe Alaric e administrar Valdren.",
      "Para seus aliados, os Valerius são a única força capaz de impedir uma guerra civil.",
      "Para seus críticos, estão usando a infância do príncipe para controlar o reino.",
      "O símbolo da Casa é uma coroa de prata sobre um fundo azul-escuro.",
    ].join("\n\n"),
    strength: "Autoridade política, diplomacia e acesso à Guarda Real.",
    weakness:
      "Depende da legitimidade da Coroa e precisa manter as outras Casas unidas.",
    publicInterest: "Preservar o reino e impedir que a crise destrua a regência.",
    privateIntroduction: [
      "Você é Lady Celene Valerius.",
      "Sua responsabilidade é manter Valdren unido até que o príncipe Alaric possa assumir a Coroa.",
      "Isso parece cada vez menos possível.",
      "Os lordes do sul dizem que a ameaça foi criada pela incompetência da Casa Vargen. Alguns nobres querem retirar tropas da fronteira para proteger suas próprias terras.",
      "A Guilda do Ferro exige pagamento antecipado para aumentar a produção de armas.",
      "A Casa Auremont se recusa a revelar seus estoques verdadeiros.",
      "A Ordem do Sino teme que uma declaração pública sobre mortos-vivos provoque pânico religioso.",
      "E a Irmandade dos Corvos sabe mais do que admite.",
      "Você possui ainda uma informação que não compartilhou com ninguém.",
      "Três dias antes de morrer, o rei Edric ordenou que antigos documentos sobre a dinastia de Halric V fossem removidos dos arquivos reais.",
      "O rei parecia assustado.",
      "Ele lhe disse:",
      "Há nomes que as Brumas não esqueceram.",
      "Depois de sua morte, os documentos desapareceram.",
      "Na noite passada, você encontrou um deles sobre sua mesa.",
      "Ninguém foi visto entrando em seus aposentos.",
      "O documento descreve uma expedição real enviada ao Norte cento e cinquenta anos atrás. O comandante era o príncipe Othmar, irmão mais novo de Halric V.",
      "A expedição nunca retornou.",
      "O nome de Othmar foi posteriormente removido de todos os registros oficiais.",
    ].join("\n\n"),
    privateObjective: "Manter Unidade acima de dois e proteger o príncipe Alaric.",
    privateConcern: "O Rei Pálido pode possuir uma reivindicação antiga sobre a Coroa.",
  },

  "iron-guild": {
    id: "iron-guild",
    name: "Guilda do Ferro Negro",
    subtitle: "Os Mestres das Fornalhas",
    motto: "O reino permanece onde o ferro resiste.",
    leaderName: "Mestre Torren Krail",
    publicIntroduction: [
      "A Guilda do Ferro Negro não é uma Casa nobre.",
      "É uma confederação de mineradores, ferreiros, pedreiros, engenheiros e comerciantes que controla a maior parte da produção de armas e ferramentas de Valdren.",
      "Sem a Guilda, muralhas não são reparadas, espadas não são forjadas e pontes destruídas não podem ser reconstruídas.",
      "A nobreza depende da Guilda, mas raramente a trata como igual.",
      "Os trabalhadores não esqueceram isso.",
      "O símbolo da Guilda é um martelo negro diante de uma chama vermelha.",
    ].join("\n\n"),
    strength: "Armas, fortificações, engenharia e trabalhadores especializados.",
    weakness: "Depende de minério, combustível e rotas de transporte.",
    publicInterest: "Preparar Valdren para uma guerra que poderá durar anos.",
    privateIntroduction: [
      "Você é Mestre Torren Krail.",
      "Quando recebeu a primeira descrição dos mortos, não pensou em magia.",
      "Pensou em equipamento.",
      "Cadáveres congelados ainda podem ser quebrados. Armaduras antigas ainda possuem pontos fracos. Pontes ainda podem ser derrubadas e estradas ainda podem ser bloqueadas.",
      "Entretanto, seus ferreiros descobriram algo preocupante.",
      "Uma espada recuperada de um morto encontrado perto de Varn foi colocada em uma fornalha.",
      "O metal não derreteu.",
      "Quando o ferreiro tentou martelá-lo, a lâmina começou a emitir um som semelhante a uma voz distante.",
      "Três trabalhadores afirmaram ter ouvido seus próprios nomes.",
      "Um deles entrou na fornalha durante a noite e morreu queimado.",
      "A espada permaneceu intacta.",
      "O símbolo marcado em sua lâmina pertence a uma mina chamada Korven, fechada há mais de cem anos depois que os trabalhadores encontraram ruínas sob a montanha.",
      "Os registros da Guilda indicam que a mina não deveria conter ferro.",
      "Ainda assim, alguém retirou grandes quantidades de metal de lá.",
    ].join("\n\n"),
    privateObjective:
      "Manter Força Militar acima de dois e descobrir como destruir os soldados do Lich.",
    privateConcern:
      "O inimigo pode possuir armas que as fornalhas de Valdren não conseguem destruir.",
  },

  "pale-bell": {
    id: "pale-bell",
    name: "Ordem do Sino Pálido",
    subtitle: "Guardiões dos Vivos e dos Mortos",
    motto: "Todo sino deve tocar uma última vez.",
    leaderName: "Madre Ysabet Voss",
    publicIntroduction: [
      "A Ordem do Sino Pálido administra templos, hospitais, cemitérios e casas de acolhimento.",
      "Seus sacerdotes registram nascimentos e mortes, cuidam dos feridos e conduzem os ritos funerários de quase toda a população.",
      "Em tempos de paz, a Ordem aconselha a Coroa.",
      "Em tempos de crise, pode transformar medo em esperança — ou em fanatismo.",
      "O símbolo da Ordem é um sino prateado cercado por seis velas.",
    ].join("\n\n"),
    strength: "Hospitais, moral, influência popular e conhecimento sobre ritos funerários.",
    weakness: "Pouco poder militar e divisões internas entre moderados e fanáticos.",
    publicInterest: "Impedir que o medo dos mortos destrua a sociedade dos vivos.",
    privateIntroduction: [
      "Você é Madre Ysabet Voss.",
      "Durante toda a sua vida, ensinou que os mortos devem receber descanso.",
      "Agora, sacerdotes do Norte enviam relatos de corpos desaparecendo de túmulos.",
      "Você acreditava que os cemitérios estavam sendo saqueados.",
      "Então recebeu uma carta do irmão Caldus, responsável pelo templo de Varn.",
      "A mensagem dizia:",
      "Eles não despertam vazios. Eles se lembram.",
      "Caldus afirmava que alguns mortos conheciam os nomes de familiares, repetiam orações e imploravam para ser queimados antes que uma voz assumisse o controle deles.",
      "A carta termina abruptamente.",
      "Junto dela veio uma pequena tira de tecido retirada das vestes de um cadáver.",
      "O tecido pertence à Ordem do Sino Pálido.",
      "Pelos registros do templo, o sacerdote que usava aquelas vestes morreu há sessenta e oito anos.",
      "Você possui textos antigos sobre liches, mas a maior parte foi proibida pela Coroa. Segundo esses textos, um lich só pode ser destruído permanentemente caso seu filactério seja encontrado.",
      "Entretanto, nenhum texto explica como um lich poderia controlar mortos através das Brumas.",
    ].join("\n\n"),
    privateObjective:
      "Aumentar Conhecimento sobre o Inimigo e impedir que o medo ou a desordem destruam a população.",
    privateConcern:
      "Os mortos podem manter parte de suas memórias e estar conscientes de tudo o que fazem.",
  },

  ravens: {
    id: "ravens",
    name: "Irmandade dos Corvos",
    subtitle: "Aqueles que Sabem Primeiro",
    motto: "Toda estrada conta uma verdade.",
    leaderName: "Nera Corvin",
    publicIntroduction: [
      "A Irmandade dos Corvos controla mensageiros, informantes, guias, contrabandistas e espiões por todo o reino.",
      "Ela começou como uma rede de entregadores criada para atravessar as estradas perigosas próximas às Brumas. Com o tempo, tornou-se uma organização capaz de descobrir segredos antes mesmo que seus proprietários percebam que os perderam.",
      "As Casas utilizam seus serviços e, ao mesmo tempo, desconfiam dela.",
      "O símbolo da Irmandade é um corvo negro carregando uma chave.",
    ].join("\n\n"),
    strength: "Espionagem, comunicação, infiltração e rotas clandestinas.",
    weakness: "Poucos soldados e baixa confiança das demais facções.",
    publicInterest:
      "Descobrir quem é o Rei Pálido e como seu poder atravessa as Brumas.",
    privateIntroduction: [
      "Você é Nera Corvin.",
      "Seus agentes estavam no Norte antes das primeiras fortalezas caírem.",
      "Alguns trabalhavam como mercadores. Outros como soldados, criados e contrabandistas.",
      "Quase todos desapareceram.",
      "Um deles retornou.",
      "Seu nome é Garran. Ele entrou na sede da Irmandade durante a madrugada e entregou um mapa das estradas ao norte de Varn.",
      "Garran parecia normal, exceto pelo fato de não respirar.",
      "Depois de entregar o mapa, disse:",
      "Ele encontrou uma estrada através dos mortos.",
      "Então caiu.",
      "O corpo estava congelado por dentro.",
      "O mapa mostra rotas atravessando as Brumas e ligando Valdren a lugares desconhecidos. Em uma dessas regiões, há uma cidade cercada por muralhas e por milhares de cadáveres.",
      "No centro do mapa, Garran desenhou uma torre.",
      "Abaixo dela escreveu:",
      "O coração não está no Norte.",
      "Você acredita que essa frase se refere ao filactério do Lich.",
      "Se estiver correta, destruir seu exército não será suficiente.",
    ].join("\n\n"),
    privateObjective:
      "Descobrir três pistas sobre a identidade, o poder ou o filactério do Rei Pálido.",
    privateConcern: "O filactério pode estar escondido em Valdren.",
  },
};
