import type { ProjectTemplate } from "./projects.js";

const ce = (over: Partial<ProjectTemplate["completionEffects"]> = {}) => ({
  attributeChanges: [],
  favors: [],
  assets: [],
  qualitativeEffects: [],
  unlocks: [],
  ...over,
});

const w = (n: number) => ({ type: "WEALTH" as const, amount: n, timing: "ON_START" as const });
const r = (n: number) => ({ type: "RESOURCES" as const, amount: n, timing: "ON_START" as const });
const st = (n: number) => ({ type: "STABILITY" as const, amount: n, timing: "ON_START" as const });
const sol = (n: number) => ({ type: "SOLDIERS_COMMITTED" as const, amount: n, timing: "ON_START" as const });
const ctrl = (n: number) => ({ type: "CONTROL_COMMITTED" as const, amount: n, timing: "ON_START" as const });
const custom = (note: string) => ({ type: "CUSTOM" as const, amount: 1, timing: "ON_START" as const, note });

export const DEFAULT_PROJECT_TEMPLATES: ProjectTemplate[] = [
  // ── MILITARY ──────────────────────────────────────────────────────────────
  {
    id: "recrutar-companhias-errantes",
    title: "Recrutar Companhias Errantes",
    category: "MILITARY",
    durationTurns: 3,
    costs: [w(1), st(1)],
    requirements: ["acesso a povo errante/mercenário"],
    description: "Recruta companhias errantes ou mercenárias para reforçar os soldados da Casa.",
    completionEffects: ce({
      attributeChanges: [{ attribute: "soldados", amount: 1, permanent: true }],
      qualitativeEffects: ["Soldados +1 permanente."],
    }),
    risks: ["exigem terras, pagamento ou direitos em troca do serviço"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "treinar-a-milicia-popular",
    title: "Treinar a Milícia Popular",
    category: "MILITARY",
    durationTurns: 2,
    costs: [r(1)],
    requirements: [],
    description: "Organiza e treina a população local como milícia defensiva do território.",
    completionEffects: ce({
      assets: ["Milícia Local"],
      qualitativeEffects: [
        "Concede o ativo 'Milícia Local': bônus defensivo no território.",
        "Não aumenta Soldados permanentemente.",
      ],
    }),
    risks: ["retirada de trabalhadores da produção afeta a economia local"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-uma-academia-de-oficiais",
    title: "Fundar uma Academia de Oficiais",
    category: "MILITARY",
    durationTurns: 5,
    costs: [w(2), r(1)],
    requirements: [],
    description: "Funda uma academia para formar e profissionalizar os oficiais militares da Casa.",
    completionEffects: ce({
      qualitativeEffects: [
        "+1 Controle durante ações militares.",
        "Permite reorganizar uma unidade derrotada 1x por ciclo.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fortificar-a-fronteira",
    title: "Fortificar a Fronteira",
    category: "MILITARY",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói muralhas, torres e obstáculos para fortalecer a fronteira do território.",
    completionEffects: ce({
      assets: ["Fronteira Fortificada"],
      qualitativeEffects: [
        "Concede o ativo 'Fronteira Fortificada': invasores gastam mais recursos.",
        "+1 Controle temporário em defesa contra invasões.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-torres-de-sinalizacao",
    title: "Construir Torres de Sinalização",
    category: "MILITARY",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Ergue uma rede de torres de sinalização para comunicação rápida e vigilância do território.",
    completionEffects: ce({
      qualitativeEffects: [
        "Nenhum ataque pode surpreender totalmente a Casa.",
        "Mensagens militares trafegam mais rapidamente.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-uma-rede-de-batedores",
    title: "Criar uma Rede de Batedores",
    category: "MILITARY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Estabelece uma rede de batedores para monitorar movimentações inimigas no território.",
    completionEffects: ce({
      qualitativeEffects: [
        "Informações antecipadas sobre movimentações de tropas e eventos territoriais.",
        "Permite uma investigação territorial extra durante crises.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "domesticar-animais-de-guerra",
    title: "Domesticar Animais de Guerra",
    category: "MILITARY",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Treina e domestica animais para uso em combate, criando uma força auxiliar diferenciada.",
    completionEffects: ce({
      assets: ["Animais de Guerra"],
      qualitativeEffects: ["Concede o ativo 'Animais de Guerra' para uso em conflitos militares."],
    }),
    risks: ["acidentes durante o treinamento e possível oposição cultural"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-um-arsenal-regional",
    title: "Construir um Arsenal Regional",
    category: "MILITARY",
    durationTurns: 4,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Constrói um arsenal para estocar armas e equipamentos militares da região.",
    completionEffects: ce({
      qualitativeEffects: ["A próxima mobilização militar custa -1 Recurso."],
    }),
    risks: ["risco de sabotagem ou confisco por forças inimigas"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "contratar-uma-companhia-mercenaria",
    title: "Contratar uma Companhia Mercenária",
    category: "MILITARY",
    durationTurns: 1,
    costs: [w(2)],
    requirements: [],
    description: "Contrata mercenários para reforço temporário das forças militares da Casa.",
    completionEffects: ce({
      qualitativeEffects: ["+1 Soldados temporário por 2 turnos."],
    }),
    risks: ["mercenários podem trocar de lado se receberem melhor oferta"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "formar-uma-guarda-de-elite",
    title: "Formar uma Guarda de Elite",
    category: "MILITARY",
    durationTurns: 4,
    costs: [w(2)],
    requirements: [],
    description: "Seleciona e treina os melhores guerreiros para compor uma guarda de elite pessoal.",
    completionEffects: ce({
      assets: ["Guarda de Elite"],
      qualitativeEffects: ["Concede o ativo 'Guarda de Elite' com capacidades especiais em combate."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "expandir-a-frota",
    title: "Expandir a Frota",
    category: "MILITARY",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: ["porto ou estaleiro disponível"],
    description: "Constrói novos navios de guerra para expandir o poder naval da Casa.",
    completionEffects: ce({
      qualitativeEffects: [
        "+1 Soldados em conflitos marítimos.",
        "Permite transporte naval de tropas e suprimentos.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "preparar-reservas-de-guerra",
    title: "Preparar Reservas de Guerra",
    category: "MILITARY",
    durationTurns: 3,
    costs: [r(2)],
    requirements: [],
    description: "Acumula suprimentos e reservas estratégicas para sustentar campanhas militares prolongadas.",
    completionEffects: ce({
      qualitativeEffects: ["Sustenta uma campanha por 2 turnos sem custo de manutenção."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── INFRASTRUCTURE ────────────────────────────────────────────────────────
  {
    id: "construir-um-aqueduto",
    title: "Construir um Aqueduto",
    category: "INFRASTRUCTURE",
    durationTurns: 5,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Constrói um aqueduto para garantir fornecimento estável de água ao território.",
    completionEffects: ce({
      qualitativeEffects: [
        "+1 Recursos OU +1 Estabilidade (escolha na conclusão).",
        "Resistência a secas e cercos prolongados.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-um-grande-celeiro",
    title: "Construir um Grande Celeiro",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Ergue um grande celeiro para armazenar alimentos e proteger o território da fome.",
    completionEffects: ce({
      assets: ["Reservas de Alimento"],
      qualitativeEffects: ["Concede o ativo 'Reservas de Alimento': proteção contra crises de fome."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── ECONOMY ───────────────────────────────────────────────────────────────
  {
    id: "abrir-uma-nova-mina",
    title: "Abrir uma Nova Mina",
    category: "ECONOMY",
    durationTurns: 5,
    costs: [r(2), w(1)],
    requirements: ["território com depósitos minerais acessíveis"],
    description: "Abre uma nova mina para extrair recursos minerais e aumentar a produção permanente.",
    completionEffects: ce({
      attributeChanges: [{ attribute: "recursos", amount: 1, permanent: true }],
      qualitativeEffects: ["Recursos +1 permanente."],
    }),
    risks: ["risco de acidente, criatura ou conflito por direitos sobre a mina"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "restaurar-uma-estrada-real",
    title: "Restaurar uma Estrada Real",
    category: "INFRASTRUCTURE",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Restaura e mantém uma estrada real para facilitar viagens e o comércio regional.",
    completionEffects: ce({
      qualitativeEffects: [
        "Viagens e movimentações tropas/comércio tornam-se mais rápidas.",
        "Vantagem comercial inicial em negociações com territórios conectados.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-uma-ponte-fortificada",
    title: "Construir uma Ponte Fortificada",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói uma ponte estratégica sobre um rio para melhorar comércio e defesa.",
    completionEffects: ce({
      qualitativeEffects: [
        "Melhora comércio e defesa sobre o rio.",
        "Permite cobrar pedágio e controlar a passagem de tropas e mercadorias.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "expandir-o-porto",
    title: "Expandir o Porto",
    category: "ECONOMY",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: [],
    description: "Expande o porto para ampliar o comércio marítimo e aumentar a riqueza permanente.",
    completionEffects: ce({
      attributeChanges: [{ attribute: "riqueza", amount: 1, permanent: true }],
      qualitativeEffects: [
        "Riqueza +1 permanente.",
        "Possível rivalidade com portos próximos de outras Casas.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-mercado-regional",
    title: "Criar um Mercado Regional",
    category: "ECONOMY",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Funda um mercado regional para centralizar trocas comerciais e aumentar a riqueza permanente.",
    completionEffects: ce({
      attributeChanges: [{ attribute: "riqueza", amount: 1, permanent: true }],
      qualitativeEffects: [
        "Riqueza +1 permanente.",
        "Bônus em negociações comerciais realizadas neste território.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "estabelecer-uma-rota-de-caravanas",
    title: "Estabelecer uma Rota de Caravanas",
    category: "ECONOMY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: ["caminho seguro entre os territórios participantes"],
    description: "Estabelece uma rota de caravanas entre territórios para gerar benefício comercial mútuo.",
    completionEffects: ce({
      qualitativeEffects: ["Benefício comercial contínuo para todos os participantes da rota."],
    }),
    risks: ["a rota pode ser atacada ou bloqueada por forças inimigas"],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "construir-oficinas-reais",
    title: "Construir Oficinas Reais",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói oficinas reais para produção especializada e aceleração de projetos futuros.",
    completionEffects: ce({
      qualitativeEffects: ["-1 turno na duração do próximo projeto de construção."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "drenar-pantanos-e-recuperar-terras",
    title: "Drenar Pântanos e Recuperar Terras",
    category: "INFRASTRUCTURE",
    durationTurns: 5,
    costs: [r(2)],
    requirements: [],
    description: "Drena pântanos para recuperar terras agricultáveis e expandir o território produtivo.",
    completionEffects: ce({
      qualitativeEffects: [
        "+1 Recursos OU fundação de uma nova comunidade agrícola (escolha na conclusão).",
      ],
    }),
    risks: ["risco de doenças, danos ao ecossistema ou descoberta de ruínas perigosas"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-sistema-de-irrigacao",
    title: "Criar um Sistema de Irrigação",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói canais de irrigação para melhorar as colheitas e a produtividade agrícola.",
    completionEffects: ce({
      qualitativeEffects: [
        "Melhora colheitas e produtividade agrícola.",
        "+1 Recursos após a primeira colheita em território agrícola irrigado.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-um-estaleiro",
    title: "Fundar um Estaleiro",
    category: "INFRASTRUCTURE",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: ["acesso a rio navegável ou litoral"],
    description: "Funda um estaleiro para construção e manutenção de embarcações da Casa.",
    completionEffects: ce({
      assets: ["Estaleiro"],
      qualitativeEffects: [
        "Concede o ativo 'Estaleiro': permite executar projetos navais e construir embarcações.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── DIPLOMACY (all requiresTargetApproval: true) ──────────────────────────
  {
    id: "enviar-um-presente-cerimonial",
    title: "Enviar um Presente Cerimonial",
    category: "DIPLOMACY",
    durationTurns: 1,
    costs: [w(1)],
    requirements: [],
    description: "Envia um presente cerimonial a outra Casa para demonstrar boa vontade e abrir diálogo.",
    completionEffects: ce({
      qualitativeEffects: ["Demonstra boa vontade; possibilidade de receber 1 Favor em retribuição."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "oferecer-ajuda-durante-uma-crise",
    title: "Oferecer Ajuda Durante uma Crise",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [custom("conforme o tipo de ajuda oferecida")],
    requirements: [],
    description: "Oferece ajuda concreta a outra Casa durante uma crise para ganhar influência e Favor.",
    completionEffects: ce({
      qualitativeEffects: ["Concede 1 Favor se a ajuda resolver o problema real da Casa alvo."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "realizar-um-grande-banquete",
    title: "Realizar um Grande Banquete",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [w(2)],
    requirements: [],
    description: "Organiza um grande banquete para reunir aliados e abrir negociações diplomáticas.",
    completionEffects: ce({
      qualitativeEffects: ["Convida até 3 Casas para participar de negociações formais."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "propor-um-casamento-politico",
    title: "Propor um Casamento Político",
    category: "DIPLOMACY",
    durationTurns: 4,
    costs: [w(1)],
    requirements: [],
    description: "Propõe uma aliança matrimonial com outra Casa para criar um vínculo dinástico duradouro.",
    completionEffects: ce({
      qualitativeEffects: [
        "Cria vínculo dinástico com a Casa alvo.",
        "Possibilidade de receber 1 Favor e gerar novas reivindicações políticas.",
      ],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: true,
  },
  {
    id: "enviar-uma-delegacao-permanente",
    title: "Enviar uma Delegação Permanente",
    category: "DIPLOMACY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Instala uma delegação permanente na corte de outra Casa para facilitar negociações contínuas.",
    completionEffects: ce({
      qualitativeEffects: [
        "Estabelece embaixada permanente com a Casa alvo.",
        "Melhora acesso a informações e eficiência em negociações futuras.",
      ],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "perdoar-uma-divida",
    title: "Perdoar uma Dívida",
    category: "DIPLOMACY",
    durationTurns: 1,
    costs: [custom("valor da dívida perdoada")],
    requirements: [],
    description: "Perdoa formalmente uma dívida de outra Casa para ganhar boa vontade e Favor.",
    completionEffects: ce({
      qualitativeEffects: [
        "Concede 1 Favor ou aumenta boa vontade.",
        "Possível melhora de Estabilidade pela demonstração de magnanimidade.",
      ],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "oferecer-protecao-militar",
    title: "Oferecer Proteção Militar",
    category: "DIPLOMACY",
    durationTurns: 1,
    costs: [sol(1)],
    requirements: [],
    description: "Oferece proteção militar a uma Casa aliada em troca de Favor e fortalecimento do vínculo.",
    completionEffects: ce({
      qualitativeEffects: ["Recebe 1 Favor após cumprir a proteção acordada."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-tratado-comercial",
    title: "Criar um Tratado Comercial",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Negocia um tratado comercial com outra Casa para gerar benefício econômico mútuo.",
    completionEffects: ce({
      qualitativeEffects: [
        "Benefício comercial mútuo estabelecido.",
        "Possibilidade de +1 Riqueza para ambas as Casas após 3 turnos.",
      ],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "financiar-um-projeto-estrangeiro",
    title: "Financiar um Projeto Estrangeiro",
    category: "DIPLOMACY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Financia um projeto de outra Casa para garantir Favor e participação nos resultados.",
    completionEffects: ce({
      qualitativeEffects: ["Recebe 1 Favor e participação nos frutos do projeto financiado."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "receber-refugiados-de-outra-casa",
    title: "Receber Refugiados de Outra Casa",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [r(1)],
    requirements: [],
    description: "Acolhe refugiados de outra Casa, ganhando boa vontade, mão de obra e possível Favor.",
    completionEffects: ce({
      qualitativeEffects: [
        "Ganha boa vontade da Casa de origem e mão de obra adicional.",
        "Possibilidade de receber 1 Favor.",
      ],
    }),
    risks: ["redução temporária de Estabilidade pela integração dos refugiados"],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "realizar-intercambio-de-estudiosos",
    title: "Realizar Intercâmbio de Estudiosos",
    category: "DIPLOMACY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Organiza o intercâmbio de estudiosos com outra Casa para troca de conhecimento e benefícios.",
    completionEffects: ce({
      qualitativeEffects: [
        "Troca de conhecimento especializado entre as Casas.",
        "Desbloqueia uma carta ou projeto adicional.",
      ],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "mediar-uma-disputa",
    title: "Mediar uma Disputa",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [],
    requirements: [],
    description: "Atua como mediador em uma disputa entre outras Casas para ganhar Favor de ambos os lados.",
    completionEffects: ce({
      qualitativeEffects: ["Recebe 1 Favor de cada parte se ambas aceitarem a mediação."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  // ── INTELLIGENCE ──────────────────────────────────────────────────────────
  {
    id: "estabelecer-uma-rede-de-informantes",
    title: "Estabelecer uma Rede de Informantes",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [w(2)],
    requirements: [],
    description: "Monta uma rede de informantes para coletar inteligência sobre regiões e Casas rivais.",
    completionEffects: ce({
      qualitativeEffects: [
        "Permite fazer perguntas privadas ao GM sobre uma região ou Casa específica.",
      ],
    }),
    risks: ["risco de exposição da rede e represálias"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "infiltrar-um-agente",
    title: "Infiltrar um Agente",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Infiltra um agente secreto na estrutura de uma Casa rival para obter informações específicas.",
    completionEffects: ce({
      qualitativeEffects: ["Obtém uma informação específica e secreta sobre a Casa alvo."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-uma-unidade-de-contraespionagem",
    title: "Criar uma Unidade de Contraespionagem",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [w(1), ctrl(1)],
    requirements: [],
    description: "Cria uma unidade especializada para detectar e neutralizar agentes inimigos infiltrados.",
    completionEffects: ce({
      qualitativeEffects: [
        "Reduz a eficácia de infiltrações inimigas no território.",
        "Identifica a origem de ações de espionagem detectadas.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "mapear-rotas-secretas",
    title: "Mapear Rotas Secretas",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [r(1)],
    requirements: [],
    description: "Explora e mapeia rotas secretas para movimentação discreta de tropas e agentes.",
    completionEffects: ce({
      qualitativeEffects: [
        "Descobre uma rota alternativa para movimentação sigilosa.",
        "Reduz o tempo de expedições futuras por essa rota.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "interrogar-prisioneiros",
    title: "Interrogar Prisioneiros",
    category: "INTELLIGENCE",
    durationTurns: 1,
    costs: [w(1)],
    requirements: [],
    description: "Interroga prisioneiros capturados para extrair informações sobre o inimigo.",
    completionEffects: ce({
      qualitativeEffects: [
        "Obtém informações sobre forças ou planos inimigos (precisão variável).",
        "Métodos cruéis podem resultar em -1 Estabilidade.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "decifrar-documentos-antigos",
    title: "Decifrar Documentos Antigos",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Analisa e decifra documentos antigos para revelar segredos históricos ou reivindicações.",
    completionEffects: ce({
      qualitativeEffects: [
        "Revela informação histórica, reivindicação territorial ou segredo político.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "espalhar-propaganda",
    title: "Espalhar Propaganda",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Dissemina propaganda para melhorar a imagem da Casa ou prejudicar rivais.",
    completionEffects: ce({
      qualitativeEffects: [
        "Melhora a imagem pública da própria Casa OU prejudica a reputação de outra Casa.",
      ],
    }),
    risks: ["-1 Estabilidade se a campanha de propaganda for descoberta"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "investigar-o-fluxo-do-dinheiro",
    title: "Investigar o Fluxo do Dinheiro",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Rastreia transações financeiras para identificar financiadores de atividades suspeitas.",
    completionEffects: ce({
      qualitativeEffects: ["Identifica financiadores e beneficiários de projetos ou conspirações."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "vigiar-uma-estrada-ou-porto",
    title: "Vigiar uma Estrada ou Porto",
    category: "INTELLIGENCE",
    durationTurns: 1,
    costs: [sol(1)],
    requirements: [],
    description: "Posiciona soldados para vigiar uma estrada ou porto e registrar toda a movimentação.",
    completionEffects: ce({
      qualitativeEffects: ["Registra todas as movimentações de tropas, mercadorias e pessoas no ponto vigiado."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "plantar-uma-informacao-falsa",
    title: "Plantar uma Informação Falsa",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Planta informações falsas para induzir o inimigo a cometer erros estratégicos.",
    completionEffects: ce({
      qualitativeEffects: ["Induz o inimigo a tomar uma decisão errônea com base na desinformação."],
    }),
    risks: ["perda de confiança diplomática se a desinformação for descoberta"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── SOCIETY ───────────────────────────────────────────────────────────────
  {
    id: "realizar-um-festival-popular",
    title: "Realizar um Festival Popular",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [w(1), r(1)],
    requirements: [],
    description: "Organiza um festival popular para elevar o ânimo do povo e aumentar a Estabilidade.",
    completionEffects: ce({
      qualitativeEffects: [
        "+1 Estabilidade temporária OU remove uma penalidade de Estabilidade existente.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "distribuir-alimentos",
    title: "Distribuir Alimentos",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [r(1)],
    requirements: [],
    description: "Distribui alimentos à população para evitar crises de fome e perdas de Estabilidade.",
    completionEffects: ce({
      qualitativeEffects: ["Impede a perda de Estabilidade decorrente de escassez de alimentos."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-um-hospital",
    title: "Fundar um Hospital",
    category: "SOCIETY",
    durationTurns: 4,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Funda um hospital para cuidar da população e aumentar permanentemente a Estabilidade.",
    completionEffects: ce({
      attributeChanges: [{ attribute: "stability", amount: 1, permanent: true }],
      qualitativeEffects: [
        "Estabilidade +1 permanente.",
        "Reduz perdas de Estabilidade durante epidemias e guerras.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "reformar-a-justica-local",
    title: "Reformar a Justiça Local",
    category: "SOCIETY",
    durationTurns: 4,
    costs: [w(1)],
    requirements: ["Controle >= 3"],
    description: "Reforma o sistema de justiça local para aumentar Estabilidade ou Controle.",
    completionEffects: ce({
      qualitativeEffects: ["+1 Estabilidade OU +1 Controle (escolha na conclusão)."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "realizar-um-censo",
    title: "Realizar um Censo",
    category: "SOCIETY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Realiza um censo para mapear a população e melhorar a administração do território.",
    completionEffects: ce({
      qualitativeEffects: ["Melhora a eficiência de arrecadação de impostos e de recrutamento militar."],
    }),
    risks: ["desconfiança de minorias étnicas ou religiosas pode gerar tensões"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-uma-escola-de-escribas",
    title: "Construir uma Escola de Escribas",
    category: "SOCIETY",
    durationTurns: 4,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Constrói uma escola para formar escribas e melhorar a administração e burocracia da Casa.",
    completionEffects: ce({
      qualitativeEffects: [
        "Melhora a eficiência administrativa da Casa.",
        "-1 turno na duração do próximo projeto de Controle ou diplomacia.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "reconhecer-uma-tradicao-local",
    title: "Reconhecer uma Tradição Local",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [],
    requirements: [],
    description: "Reconhece oficialmente uma tradição local para ganhar a lealdade da comunidade.",
    completionEffects: ce({
      qualitativeEffects: [
        "+Dignidade perante a comunidade local.",
        "Possibilidade de +1 Estabilidade pela demonstração de respeito cultural.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "conceder-anistia",
    title: "Conceder Anistia",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [],
    requirements: [],
    description: "Concede anistia a grupos em conflito com a Casa para reduzir tensões internas.",
    completionEffects: ce({
      qualitativeEffects: ["Reduz tensões internas e pode estabilizar regiões em conflito."],
    }),
    risks: ["pode ser interpretado como fraqueza política por rivais"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-fundo-para-viuvas-e-orfaos",
    title: "Criar um Fundo para Viúvas e Órfãos",
    category: "SOCIETY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Cria um fundo de assistência para viúvas e órfãos de guerra, protegendo a Estabilidade.",
    completionEffects: ce({
      qualitativeEffects: ["Impede a perda de Estabilidade após guerras ou eventos de grandes baixas."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "erguer-um-monumento-aos-mortos",
    title: "Erguer um Monumento aos Mortos",
    category: "SOCIETY",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Ergue um monumento em homenagem aos mortos para elevar a Dignidade e a Estabilidade.",
    completionEffects: ce({
      qualitativeEffects: [
        "+Dignidade perante o povo e outras Casas.",
        "Possibilidade de +1 Estabilidade após uma tragédia recente.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── EXPLORATION / MAGIC ───────────────────────────────────────────────────
  {
    id: "enviar-uma-expedicao-as-ruinas",
    title: "Enviar uma Expedição às Ruínas",
    category: "EXPLORATION",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Envia uma expedição a ruínas antigas em busca de conhecimento, riqueza ou artefatos.",
    completionEffects: ce({
      qualitativeEffects: [
        "Retorna com conhecimento, riqueza, artefato ou revela uma nova ameaça — dependendo da região.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "investigar-uma-alteracao-nas-brumas",
    title: "Investigar uma Alteração nas Brumas",
    category: "EXPLORATION",
    durationTurns: 3,
    costs: [w(1)],
    requirements: ["acesso a magos ou estudiosos do sobrenatural"],
    description: "Investiga uma perturbação nas Brumas para compreender padrões mágicos e riscos ocultos.",
    completionEffects: ce({
      qualitativeEffects: [
        "Revela informações sobre padrões das Brumas, riscos e possíveis rotas além delas.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "contratar-a-ordem-dos-tres",
    title: "Contratar a Ordem dos Três",
    category: "MAGIC",
    durationTurns: 3,
    costs: [w(2)],
    requirements: [],
    description: "Contrata a enigmática Ordem dos Três para realizar um ritual mágico específico.",
    completionEffects: ce({
      qualitativeEffects: ["Execução de um ritual mágico específico acordado com a Ordem dos Três."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: true,
  },
  {
    id: "construir-protecoes-arcanas",
    title: "Construir Proteções Arcanas",
    category: "MAGIC",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: [],
    description: "Erige proteções mágicas ao redor do território para defender contra ameaças arcanas.",
    completionEffects: ce({
      assets: ["Proteções Arcanas"],
      qualitativeEffects: [
        "Concede o ativo 'Proteções Arcanas': defesa contra um tipo específico de magia ou ameaça arcana.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-um-observatorio",
    title: "Fundar um Observatório",
    category: "EXPLORATION",
    durationTurns: 5,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Constrói um observatório para estudo dos astros, auxiliando em previsões e navegação.",
    completionEffects: ce({
      assets: ["Observatório"],
      qualitativeEffects: [
        "Concede o ativo 'Observatório': melhora previsões climáticas e auxilia na navegação.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "pesquisar-um-artefato",
    title: "Pesquisar um Artefato",
    category: "MAGIC",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Pesquisa a origem, função e riscos de um artefato misterioso em posse da Casa.",
    completionEffects: ce({
      qualitativeEffects: ["Revela a origem, função e possíveis riscos do artefato estudado."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: true,
  },
  {
    id: "criar-uma-biblioteca-regional",
    title: "Criar uma Biblioteca Regional",
    category: "EXPLORATION",
    durationTurns: 5,
    costs: [w(2), r(1)],
    requirements: [],
    description: "Funda uma biblioteca regional para preservar conhecimento e desbloquear pesquisas avançadas.",
    completionEffects: ce({
      assets: ["Biblioteca Regional"],
      qualitativeEffects: [
        "Concede o ativo 'Biblioteca Regional': desbloqueia projetos de pesquisa e estudo avançados.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "organizar-uma-expedicao-alem-das-fronteiras",
    title: "Organizar uma Expedição Além das Fronteiras",
    category: "EXPLORATION",
    durationTurns: 4,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Organiza uma expedição além das fronteiras conhecidas para explorar territórios e povos.",
    completionEffects: ce({
      qualitativeEffects: [
        "Descobre novo território, povo, rota comercial ou ameaça desconhecida.",
      ],
    }),
    risks: ["parte da expedição pode não retornar"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
];

export function getTemplate(id: string): ProjectTemplate | undefined {
  return DEFAULT_PROJECT_TEMPLATES.find((t) => t.id === id);
}
