import type { ProjectTemplate } from "./projects.js";

const ce = (over: Partial<ProjectTemplate["completionEffects"]> = {}) => ({
  attributeChanges: [],
  favors: [],
  assets: [],
  qualitativeEffects: [],
  unlocks: [],
  ...over,
});

const w = (n: number) => ({ type: "WEALTH" as const, amount: n, timing: "ON_START" as const });
const r = (n: number) => ({ type: "RESOURCES" as const, amount: n, timing: "ON_START" as const });
const st = (n: number) => ({ type: "STABILITY" as const, amount: n, timing: "ON_START" as const });
const sol = (n: number) => ({ type: "SOLDIERS_COMMITTED" as const, amount: n, timing: "ON_START" as const });
const ctrl = (n: number) => ({ type: "CONTROL_COMMITTED" as const, amount: n, timing: "ON_START" as const });
const custom = (note: string) => ({ type: "CUSTOM" as const, amount: 1, timing: "ON_START" as const, note });

/**
 * Marcador da Casa alvo da carta. Cartas de Diplomacia só sabem a quem devem o
 * Favor quando o jogador escolhe o alvo, então o modelo guarda este lugar e o
 * alvo real da carta ocupa a posição na hora da conclusão.
 */
const ALVO_DA_CARTA = "TARGET";

/** Um Favor devido pela Casa alvo, a moeda natural da Diplomacia. */
const favor = (n = 1) => [{ targetHouseId: ALVO_DA_CARTA, amount: n, requiresAcceptance: true }];

/** Ganho permanente de atributo: o motor descarta qualquer efeito temporário. */
const perm = (attribute: ProjectTemplate["completionEffects"]["attributeChanges"][number]["attribute"], amount: number) => ({
  attribute,
  amount,
  permanent: true,
});

export const DEFAULT_PROJECT_TEMPLATES: ProjectTemplate[] = [
  // ── MILITARY ──────────────────────────────────────────────────────────────
  {
    id: "recrutar-companhias-errantes",
    title: "Recrutar Companhias Errantes",
    category: "MILITARY",
    durationTurns: 3,
    costs: [w(1), st(1)],
    requirements: ["acesso a povo errante/mercenário"],
    description: "Recruta companhias errantes ou mercenárias para reforçar os soldados da Casa.",
    completionEffects: ce({
      attributeChanges: [{ attribute: "soldados", amount: 1, permanent: true }],
      qualitativeEffects: ["Soldados +1 permanente."],
    }),
    risks: ["exigem terras, pagamento ou direitos em troca do serviço"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "treinar-a-milicia-popular",
    title: "Treinar a Milícia Popular",
    category: "MILITARY",
    durationTurns: 2,
    costs: [r(1)],
    requirements: [],
    description: "Organiza e treina a população local como milícia defensiva do território.",
    completionEffects: ce({
      assets: ["Milícia Local"],
      unlocks: ["fortificar-a-fronteira"],
      qualitativeEffects: ["Camponeses aprendem a segurar a lança antes de segurar o medo."],
    }),
    risks: ["retirada de trabalhadores da produção afeta a economia local"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-uma-academia-de-oficiais",
    title: "Fundar uma Academia de Oficiais",
    category: "MILITARY",
    durationTurns: 5,
    costs: [w(2), r(1)],
    requirements: [],
    description: "Funda uma academia para formar e profissionalizar os oficiais militares da Casa.",
    completionEffects: ce({
      attributeChanges: [perm("soldados", 1)],
      assets: ["Academia de Oficiais"],
      qualitativeEffects: ["A Casa passa a formar seus próprios comandantes, em vez de pedi-los emprestados."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fortificar-a-fronteira",
    title: "Fortificar a Fronteira",
    category: "MILITARY",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói muralhas, torres e obstáculos para fortalecer a fronteira do território.",
    completionEffects: ce({
      attributeChanges: [perm("controle", 1)],
      assets: ["Fronteira Fortificada"],
      qualitativeEffects: ["Quem cruza a linha agora precisa pedir licença à pedra."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-torres-de-sinalizacao",
    title: "Construir Torres de Sinalização",
    category: "MILITARY",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Ergue uma rede de torres de sinalização para comunicação rápida e vigilância do território.",
    completionEffects: ce({
      assets: ["Rede de Torres de Sinalização"],
      unlocks: ["construir-um-arsenal-regional"],
      qualitativeEffects: ["De colina em colina, o fogo chega antes do cavaleiro."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-uma-rede-de-batedores",
    title: "Criar uma Rede de Batedores",
    category: "MILITARY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Estabelece uma rede de batedores para monitorar movimentações inimigas no território.",
    completionEffects: ce({
      assets: ["Rede de Batedores"],
      unlocks: ["fortificar-a-fronteira"],
      qualitativeEffects: ["Olhos que dormem de dia e contam o horizonte de noite."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "domesticar-animais-de-guerra",
    title: "Domesticar Animais de Guerra",
    category: "MILITARY",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Treina e domestica animais para uso em combate, criando uma força auxiliar diferenciada.",
    completionEffects: ce({
      assets: ["Animais de Guerra"],
      qualitativeEffects: ["O rugido chega ao campo de batalha antes da linha de frente."],
    }),
    risks: ["acidentes durante o treinamento e possível oposição cultural"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-um-arsenal-regional",
    title: "Construir um Arsenal Regional",
    category: "MILITARY",
    durationTurns: 4,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Constrói um arsenal para estocar armas e equipamentos militares da região.",
    completionEffects: ce({
      assets: ["Arsenal Regional"],
      qualitativeEffects: ["Ferro empilhado à espera de mãos — e de um motivo."],
    }),
    risks: ["risco de sabotagem ou confisco por forças inimigas"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "contratar-uma-companhia-mercenaria",
    title: "Contratar uma Companhia Mercenária",
    category: "MILITARY",
    durationTurns: 1,
    costs: [w(1)],
    requirements: [],
    description: "Contrata mercenários para reforço temporário das forças militares da Casa.",
    completionEffects: ce({
      assets: ["Companhia Mercenária"],
      qualitativeEffects: ["Lâminas alugadas, lealdade alugada, prazo combinado."],
    }),
    risks: ["mercenários podem trocar de lado se receberem melhor oferta"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "formar-uma-guarda-de-elite",
    title: "Formar uma Guarda de Elite",
    category: "MILITARY",
    durationTurns: 4,
    costs: [w(2)],
    requirements: [],
    description: "Seleciona e treina os melhores guerreiros para compor uma guarda de elite pessoal.",
    completionEffects: ce({
      assets: ["Guarda de Elite"],
      qualitativeEffects: ["Poucos, escolhidos um a um, e nenhum deles dorme quando o senhor dorme."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "expandir-a-frota",
    title: "Expandir a Frota",
    category: "MILITARY",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: ["porto ou estaleiro disponível"],
    description: "Constrói novos navios de guerra para expandir o poder naval da Casa.",
    completionEffects: ce({
      attributeChanges: [perm("soldados", 1)],
      assets: ["Frota de Guerra"],
      qualitativeEffects: ["Velas novas cobrem o ancoradouro como um segundo horizonte."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "preparar-reservas-de-guerra",
    title: "Preparar Reservas de Guerra",
    category: "MILITARY",
    durationTurns: 3,
    costs: [r(2)],
    requirements: [],
    description: "Acumula suprimentos e reservas estratégicas para sustentar campanhas militares prolongadas.",
    completionEffects: ce({
      assets: ["Reservas de Guerra"],
      qualitativeEffects: ["Grãos, ferraduras e sal guardados para o inverno que ninguém quer nomear."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── INFRASTRUCTURE ────────────────────────────────────────────────────────
  {
    id: "construir-um-aqueduto",
    title: "Construir um Aqueduto",
    category: "INFRASTRUCTURE",
    durationTurns: 5,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Constrói um aqueduto para garantir fornecimento estável de água ao território.",
    completionEffects: ce({
      attributeChanges: [perm("recursos", 1)],
      assets: ["Aqueduto"],
      qualitativeEffects: ["A água chega sozinha, e a cidade esquece o que era ter sede."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-um-grande-celeiro",
    title: "Construir um Grande Celeiro",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Ergue um grande celeiro para armazenar alimentos e proteger o território da fome.",
    completionEffects: ce({
      assets: ["Reservas de Alimento"],
      unlocks: ["criar-um-sistema-de-irrigacao"],
      qualitativeEffects: ["Enquanto houver grão nas tulhas, a fome bate em outra porta."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── ECONOMY ───────────────────────────────────────────────────────────────
  {
    id: "abrir-uma-nova-mina",
    title: "Abrir uma Nova Mina",
    category: "ECONOMY",
    durationTurns: 5,
    costs: [r(2), w(1)],
    requirements: ["território com depósitos minerais acessíveis"],
    description: "Abre uma nova mina para extrair recursos minerais e aumentar a produção permanente.",
    completionEffects: ce({
      attributeChanges: [perm("recursos", 1)],
      qualitativeEffects: ["O escuro devolve minério a quem tem coragem de descer."],
    }),
    risks: ["risco de acidente, criatura ou conflito por direitos sobre a mina"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "restaurar-uma-estrada-real",
    title: "Restaurar uma Estrada Real",
    category: "INFRASTRUCTURE",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Restaura e mantém uma estrada real para facilitar viagens e o comércio regional.",
    completionEffects: ce({
      assets: ["Estrada Real"],
      unlocks: ["construir-uma-ponte-fortificada"],
      qualitativeEffects: ["A pedra antiga volta a aguentar carroça, cavalo e notícia."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-uma-ponte-fortificada",
    title: "Construir uma Ponte Fortificada",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói uma ponte estratégica sobre um rio para melhorar comércio e defesa.",
    completionEffects: ce({
      attributeChanges: [perm("controle", 1)],
      assets: ["Ponte Fortificada"],
      qualitativeEffects: ["O rio deixa de ser fronteira e passa a ser porta — com guarda."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "expandir-o-porto",
    title: "Expandir o Porto",
    category: "ECONOMY",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: [],
    description: "Expande o porto para ampliar o comércio marítimo e aumentar a riqueza permanente.",
    completionEffects: ce({
      attributeChanges: [perm("riqueza", 1)],
      assets: ["Porto Expandido"],
      qualitativeEffects: ["Mais cais, mais língua estrangeira no mercado, mais moeda no cofre."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-mercado-regional",
    title: "Criar um Mercado Regional",
    category: "ECONOMY",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Funda um mercado regional para centralizar trocas comerciais e aumentar a riqueza permanente.",
    completionEffects: ce({
      attributeChanges: [perm("riqueza", 1)],
      qualitativeEffects: ["A praça enche de pregão, e cada pregão deixa uma moeda para trás."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "estabelecer-uma-rota-de-caravanas",
    title: "Estabelecer uma Rota de Caravanas",
    category: "ECONOMY",
    durationTurns: 3,
    costs: [r(1)],
    requirements: ["caminho seguro entre os territórios participantes"],
    description: "Estabelece uma rota de caravanas entre territórios para gerar benefício comercial mútuo.",
    completionEffects: ce({
      attributeChanges: [perm("riqueza", 1)],
      qualitativeEffects: ["Mulas carregadas de mantimento voltam carregadas de prata."],
    }),
    risks: ["a rota pode ser atacada ou bloqueada por forças inimigas"],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "construir-oficinas-reais",
    title: "Construir Oficinas Reais",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói oficinas reais para produção especializada e aceleração de projetos futuros.",
    completionEffects: ce({
      attributeChanges: [perm("recursos", 1)],
      assets: ["Oficinas Reais"],
      qualitativeEffects: ["Martelos batem em turnos, e a Casa deixa de comprar o que sabe fazer."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "drenar-pantanos-e-recuperar-terras",
    title: "Drenar Pântanos e Recuperar Terras",
    category: "INFRASTRUCTURE",
    durationTurns: 5,
    costs: [w(3)],
    requirements: [],
    description: "Drena pântanos para recuperar terras agricultáveis e expandir o território produtivo.",
    completionEffects: ce({
      attributeChanges: [perm("recursos", 2)],
      qualitativeEffects: ["Onde havia lodo e mosquito, abre-se terra preta e boa."],
    }),
    risks: ["risco de doenças, danos ao ecossistema ou descoberta de ruínas perigosas"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-sistema-de-irrigacao",
    title: "Criar um Sistema de Irrigação",
    category: "INFRASTRUCTURE",
    durationTurns: 4,
    costs: [r(2)],
    requirements: [],
    description: "Constrói canais de irrigação para melhorar as colheitas e a produtividade agrícola.",
    completionEffects: ce({
      attributeChanges: [perm("recursos", 1)],
      qualitativeEffects: ["Os canais riscam o campo, e a colheita para de depender do humor do céu."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-um-estaleiro",
    title: "Fundar um Estaleiro",
    category: "INFRASTRUCTURE",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: ["acesso a rio navegável ou litoral"],
    description: "Funda um estaleiro para construção e manutenção de embarcações da Casa.",
    completionEffects: ce({
      assets: ["Estaleiro"],
      qualitativeEffects: [
        "Cheiro de piche e madeira nova toma conta da margem.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── DIPLOMACY (all requiresTargetApproval: true) ──────────────────────────
  {
    id: "enviar-um-presente-cerimonial",
    title: "Enviar um Presente Cerimonial",
    category: "DIPLOMACY",
    durationTurns: 1,
    costs: [w(1)],
    requirements: [],
    description: "Envia um presente cerimonial a outra Casa para demonstrar boa vontade e abrir diálogo.",
    completionEffects: ce({
      favors: favor(1),
      qualitativeEffects: ["O presente chega embrulhado em seda e em obrigação."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "oferecer-ajuda-durante-uma-crise",
    title: "Oferecer Ajuda Durante uma Crise",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [custom("conforme o tipo de ajuda oferecida")],
    requirements: [],
    description: "Oferece ajuda concreta a outra Casa durante uma crise para ganhar influência e Favor.",
    completionEffects: ce({
      favors: favor(1),
      qualitativeEffects: ["Ajuda oferecida na hora ruim é lembrada por muito tempo."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "realizar-um-grande-banquete",
    title: "Realizar um Grande Banquete",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Organiza um grande banquete para reunir aliados e abrir negociações diplomáticas.",
    completionEffects: ce({
      favors: favor(1),
      unlocks: ["propor-um-casamento-politico"],
      qualitativeEffects: ["Entre o vinho e o assado, alianças mudam de lugar na mesa."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "propor-um-casamento-politico",
    title: "Propor um Casamento Político",
    category: "DIPLOMACY",
    durationTurns: 4,
    costs: [w(2)],
    requirements: [],
    description: "Propõe uma aliança matrimonial com outra Casa para criar um vínculo dinástico duradouro.",
    completionEffects: ce({
      favors: favor(2),
      assets: ["Vínculo Dinástico"],
      qualitativeEffects: ["Dois nomes passam a caber no mesmo brasão."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: true,
  },
  {
    id: "enviar-uma-delegacao-permanente",
    title: "Enviar uma Delegação Permanente",
    category: "DIPLOMACY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Instala uma delegação permanente na corte de outra Casa para facilitar negociações contínuas.",
    completionEffects: ce({
      assets: ["Embaixada Permanente"],
      unlocks: ["propor-um-casamento-politico"],
      qualitativeEffects: ["Um ouvido da Casa dorme todas as noites na corte alheia."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "perdoar-uma-divida",
    title: "Perdoar uma Dívida",
    category: "DIPLOMACY",
    durationTurns: 1,
    costs: [custom("valor da dívida perdoada")],
    requirements: [],
    description: "Perdoa formalmente uma dívida de outra Casa para ganhar boa vontade e Favor.",
    completionEffects: ce({
      favors: favor(1),
      qualitativeEffects: ["O pergaminho da dívida queima diante de testemunhas."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "oferecer-protecao-militar",
    title: "Oferecer Proteção Militar",
    category: "DIPLOMACY",
    durationTurns: 1,
    costs: [sol(1)],
    requirements: [],
    description: "Oferece proteção militar a uma Casa aliada em troca de Favor e fortalecimento do vínculo.",
    completionEffects: ce({
      favors: favor(1),
      qualitativeEffects: ["Lanças estrangeiras montam guarda em portão amigo."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-tratado-comercial",
    title: "Criar um Tratado Comercial",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Negocia um tratado comercial com outra Casa para gerar benefício econômico mútuo.",
    completionEffects: ce({
      favors: favor(1),
      unlocks: ["financiar-um-projeto-estrangeiro"],
      qualitativeEffects: ["Selos lacrados garantem que a mercadoria atravesse sem perguntas."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "financiar-um-projeto-estrangeiro",
    title: "Financiar um Projeto Estrangeiro",
    category: "DIPLOMACY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Financia um projeto de outra Casa para garantir Favor e participação nos resultados.",
    completionEffects: ce({
      favors: favor(2),
      qualitativeEffects: ["O ouro é da Casa alvo; a gratidão fica registrada em outro nome."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "receber-refugiados-de-outra-casa",
    title: "Receber Refugiados de Outra Casa",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [r(1)],
    requirements: [],
    description: "Acolhe refugiados de outra Casa, ganhando boa vontade, mão de obra e possível Favor.",
    completionEffects: ce({
      favors: favor(1),
      assets: ["Bairro dos Refugiados"],
      qualitativeEffects: ["Chegam com o que carregam nos braços e com o que sabem fazer."],
    }),
    risks: ["redução temporária de Estabilidade pela integração dos refugiados"],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "realizar-intercambio-de-estudiosos",
    title: "Realizar Intercâmbio de Estudiosos",
    category: "DIPLOMACY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Organiza o intercâmbio de estudiosos com outra Casa para troca de conhecimento e benefícios.",
    completionEffects: ce({
      favors: favor(1),
      assets: ["Círculo de Estudiosos"],
      qualitativeEffects: ["Livros trocam de corte, e com eles trocam de corte certas ideias."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  {
    id: "mediar-uma-disputa",
    title: "Mediar uma Disputa",
    category: "DIPLOMACY",
    durationTurns: 2,
    costs: [],
    requirements: [],
    description: "Atua como mediador em uma disputa entre outras Casas para ganhar Favor de ambos os lados.",
    completionEffects: ce({
      favors: favor(2),
      unlocks: ["enviar-uma-delegacao-permanente"],
      qualitativeEffects: ["Quem separa a briga dos outros sai da sala devido por dois lados."],
    }),
    risks: [],
    requiresTargetApproval: true,
    requiresGmApproval: false,
  },
  // ── INTELLIGENCE ──────────────────────────────────────────────────────────
  {
    // "Em Porto Cinzento, toda lanterna ilumina alguma coisa — desde que você
    // tenha moeda suficiente." O jogador diz o assunto; o Mestre decide o que a
    // rede alcançou. Segredo muito protegido nunca é vendido: no lugar dele vem
    // uma pista de como chegar lá.
    id: "comprar-informacao-rede-das-lanternas",
    title: "Comprar Informação — A Rede das Lanternas",
    category: "INTELLIGENCE",
    durationTurns: 1,
    costs: [w(1)],
    requirements: ["um agente enviado a Porto Cinzento"],
    description:
      "Envia um agente a Porto Cinzento para comprar informação da Rede das Lanternas. Informe o assunto que deseja investigar (ex.: movimentações da Coroa, Casco Vermelho, a Asteria, uma Casa rival).",
    completionEffects: ce({
      unlocks: ["infiltrar-um-agente"],
      qualitativeEffects: [
        "O Mestre determina o que a rede descobriu conforme a dificuldade e a disponibilidade do assunto.",
        "Informação muito protegida não se compra: a rede entrega, no lugar, o fio que leva até ela.",
      ],
    }),
    risks: ["a Rede vende a quem paga: alguém pode saber que você perguntou"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "estabelecer-uma-rede-de-informantes",
    title: "Estabelecer uma Rede de Informantes",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [w(2)],
    requirements: [],
    description: "Monta uma rede de informantes para coletar inteligência sobre regiões e Casas rivais.",
    completionEffects: ce({
      assets: ["Rede de Informantes"],
      unlocks: ["criar-uma-unidade-de-contraespionagem"],
      qualitativeEffects: ["Taberneiros, criados e barqueiros: ninguém desconfia de quem serve."],
    }),
    risks: ["risco de exposição da rede e represálias"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "infiltrar-um-agente",
    title: "Infiltrar um Agente",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Infiltra um agente secreto na estrutura de uma Casa rival para obter informações específicas.",
    completionEffects: ce({
      unlocks: ["estabelecer-uma-rede-de-informantes"],
      qualitativeEffects: ["Um rosto novo entre os criados da Casa alvo, e ninguém pergunta de onde veio."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-uma-unidade-de-contraespionagem",
    title: "Criar uma Unidade de Contraespionagem",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [w(1), ctrl(1)],
    requirements: [],
    description: "Cria uma unidade especializada para detectar e neutralizar agentes inimigos infiltrados.",
    completionEffects: ce({
      assets: ["Unidade de Contraespionagem"],
      qualitativeEffects: ["Cada carta que sai da corte passa por olhos que ninguém vê."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "mapear-rotas-secretas",
    title: "Mapear Rotas Secretas",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [r(1)],
    requirements: [],
    description: "Explora e mapeia rotas secretas para movimentação discreta de tropas e agentes.",
    completionEffects: ce({
      assets: ["Mapa das Rotas Secretas"],
      qualitativeEffects: ["Trilhas de contrabandista viram caminho de exército."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "interrogar-prisioneiros",
    title: "Interrogar Prisioneiros",
    category: "INTELLIGENCE",
    durationTurns: 1,
    costs: [w(1)],
    requirements: [],
    description: "Interroga prisioneiros capturados para extrair informações sobre o inimigo.",
    completionEffects: ce({
      unlocks: ["infiltrar-um-agente"],
      qualitativeEffects: ["Alguém fala, e o que fala nem sempre é o que sabe."],
    }),
    risks: ["métodos cruéis abalam a Estabilidade e mancham o nome da Casa"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "decifrar-documentos-antigos",
    title: "Decifrar Documentos Antigos",
    category: "INTELLIGENCE",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Analisa e decifra documentos antigos para revelar segredos históricos ou reivindicações.",
    completionEffects: ce({
      assets: ["Arquivo Decifrado"],
      unlocks: ["criar-uma-unidade-de-contraespionagem"],
      qualitativeEffects: ["Tinta velha ainda serve para reivindicar terra nova."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "espalhar-propaganda",
    title: "Espalhar Propaganda",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Dissemina propaganda para melhorar a imagem da Casa ou prejudicar rivais.",
    completionEffects: ce({
      unlocks: ["criar-uma-unidade-de-contraespionagem"],
      qualitativeEffects: ["A versão contada na praça vira a versão lembrada na história."],
    }),
    risks: ["-1 Estabilidade se a campanha de propaganda for descoberta"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "investigar-o-fluxo-do-dinheiro",
    title: "Investigar o Fluxo do Dinheiro",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Rastreia transações financeiras para identificar financiadores de atividades suspeitas.",
    completionEffects: ce({
      unlocks: ["decifrar-documentos-antigos"],
      qualitativeEffects: ["Toda conspiração deixa rastro em algum livro-caixa."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "vigiar-uma-estrada-ou-porto",
    title: "Vigiar uma Estrada ou Porto",
    category: "INTELLIGENCE",
    durationTurns: 1,
    costs: [sol(1)],
    requirements: [],
    description: "Posiciona soldados para vigiar uma estrada ou porto e registrar toda a movimentação.",
    completionEffects: ce({
      unlocks: ["mapear-rotas-secretas"],
      qualitativeEffects: ["Nada passa pelo ponto vigiado sem virar anotação."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "plantar-uma-informacao-falsa",
    title: "Plantar uma Informação Falsa",
    category: "INTELLIGENCE",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Planta informações falsas para induzir o inimigo a cometer erros estratégicos.",
    completionEffects: ce({
      unlocks: ["estabelecer-uma-rede-de-informantes"],
      qualitativeEffects: ["A mentira certa, dita no ouvido certo, marcha sozinha."],
    }),
    risks: ["perda de confiança diplomática se a desinformação for descoberta"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── SOCIETY ───────────────────────────────────────────────────────────────
  {
    id: "realizar-um-festival-popular",
    title: "Realizar um Festival Popular",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [w(1)],
    requirements: [],
    description: "Organiza um festival popular para elevar o ânimo do povo e aumentar a Estabilidade.",
    completionEffects: ce({
      assets: ["Calendário de Festas"],
      unlocks: ["erguer-um-monumento-aos-mortos"],
      qualitativeEffects: ["Por uma noite, o povo esquece a conta que não fecha."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "distribuir-alimentos",
    title: "Distribuir Alimentos",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [r(1)],
    requirements: [],
    description: "Distribui alimentos à população para evitar crises de fome e perdas de Estabilidade.",
    completionEffects: ce({
      unlocks: ["criar-um-fundo-para-viuvas-e-orfaos"],
      qualitativeEffects: ["Fila no pátio, pão na mão, e nenhum motim naquela semana."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-um-hospital",
    title: "Fundar um Hospital",
    category: "SOCIETY",
    durationTurns: 4,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Funda um hospital para cuidar da população e aumentar permanentemente a Estabilidade.",
    completionEffects: ce({
      attributeChanges: [perm("stability", 1)],
      assets: ["Hospital"],
      qualitativeEffects: ["Há um lugar onde se morre menos, e o povo sabe o caminho."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "reformar-a-justica-local",
    title: "Reformar a Justiça Local",
    category: "SOCIETY",
    durationTurns: 4,
    costs: [w(1), ctrl(1)],
    requirements: ["Controle >= 3"],
    description: "Reforma o sistema de justiça local para aumentar Estabilidade ou Controle.",
    completionEffects: ce({
      attributeChanges: [perm("stability", 1), perm("controle", 1)],
      qualitativeEffects: ["A sentença passa a valer igual para quem tem nome e para quem não tem."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "realizar-um-censo",
    title: "Realizar um Censo",
    category: "SOCIETY",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Realiza um censo para mapear a população e melhorar a administração do território.",
    completionEffects: ce({
      attributeChanges: [perm("controle", 1)],
      qualitativeEffects: ["Cada aldeia vira um número, e número não se esconde do cobrador."],
    }),
    risks: ["desconfiança de minorias étnicas ou religiosas pode gerar tensões"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "construir-uma-escola-de-escribas",
    title: "Construir uma Escola de Escribas",
    category: "SOCIETY",
    durationTurns: 4,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Constrói uma escola para formar escribas e melhorar a administração e burocracia da Casa.",
    completionEffects: ce({
      attributeChanges: [perm("controle", 1)],
      assets: ["Escola de Escribas"],
      qualitativeEffects: ["Ordem escrita chega mais longe do que ordem gritada."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "reconhecer-uma-tradicao-local",
    title: "Reconhecer uma Tradição Local",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [],
    requirements: [],
    description: "Reconhece oficialmente uma tradição local para ganhar a lealdade da comunidade.",
    completionEffects: ce({
      unlocks: ["erguer-um-monumento-aos-mortos"],
      qualitativeEffects: ["O costume antigo ganha selo da Casa, e a comunidade percebe."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "conceder-anistia",
    title: "Conceder Anistia",
    category: "SOCIETY",
    durationTurns: 1,
    costs: [],
    requirements: [],
    description: "Concede anistia a grupos em conflito com a Casa para reduzir tensões internas.",
    completionEffects: ce({
      unlocks: ["reformar-a-justica-local"],
      qualitativeEffects: ["Portas de cadeia abertas compram silêncio que a espada não compra."],
    }),
    risks: ["pode ser interpretado como fraqueza política por rivais"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "criar-um-fundo-para-viuvas-e-orfaos",
    title: "Criar um Fundo para Viúvas e Órfãos",
    category: "SOCIETY",
    durationTurns: 2,
    costs: [w(1)],
    requirements: [],
    description: "Cria um fundo de assistência para viúvas e órfãos de guerra, protegendo a Estabilidade.",
    completionEffects: ce({
      assets: ["Fundo das Viúvas e Órfãos"],
      unlocks: ["fundar-um-hospital"],
      qualitativeEffects: ["A viúva do soldado não precisa mendigar na porta da guarnição."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "erguer-um-monumento-aos-mortos",
    title: "Erguer um Monumento aos Mortos",
    category: "SOCIETY",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Ergue um monumento em homenagem aos mortos para elevar a Dignidade e a Estabilidade.",
    completionEffects: ce({
      attributeChanges: [perm("stability", 1)],
      assets: ["Monumento aos Mortos"],
      qualitativeEffects: ["Os nomes ficam na pedra, e o luto encontra onde se apoiar."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  // ── EXPLORATION / MAGIC ───────────────────────────────────────────────────
  {
    id: "enviar-uma-expedicao-as-ruinas",
    title: "Enviar uma Expedição às Ruínas",
    category: "EXPLORATION",
    durationTurns: 3,
    costs: [r(1), w(1)],
    requirements: [],
    description: "Envia uma expedição a ruínas antigas em busca de conhecimento, riqueza ou artefatos.",
    completionEffects: ce({
      assets: ["Achados das Ruínas"],
      unlocks: ["organizar-uma-expedicao-alem-das-fronteiras"],
      qualitativeEffects: ["Volta menos gente do que partiu, e mais coisa do que cabia na mochila."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "investigar-uma-alteracao-nas-brumas",
    title: "Investigar uma Alteração nas Brumas",
    category: "EXPLORATION",
    durationTurns: 3,
    costs: [w(1)],
    requirements: ["acesso a magos ou estudiosos do sobrenatural"],
    description: "Investiga uma perturbação nas Brumas para compreender padrões mágicos e riscos ocultos.",
    completionEffects: ce({
      assets: ["Registro das Brumas"],
      unlocks: ["fundar-um-observatorio"],
      qualitativeEffects: ["A bruma tem um desenho, e alguém finalmente o anotou."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "contratar-a-ordem-dos-tres",
    title: "Contratar a Ordem dos Três",
    category: "MAGIC",
    durationTurns: 3,
    costs: [w(2)],
    requirements: [],
    description: "Contrata a enigmática Ordem dos Três para realizar um ritual mágico específico.",
    completionEffects: ce({
      assets: ["Pacto com a Ordem dos Três"],
      unlocks: ["construir-protecoes-arcanas"],
      qualitativeEffects: ["Três vozes cobram o preço combinado, nunca um a mais, nunca um a menos."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: true,
  },
  {
    id: "construir-protecoes-arcanas",
    title: "Construir Proteções Arcanas",
    category: "MAGIC",
    durationTurns: 5,
    costs: [r(2), w(2)],
    requirements: [],
    description: "Erige proteções mágicas ao redor do território para defender contra ameaças arcanas.",
    completionEffects: ce({
      assets: ["Proteções Arcanas"],
      qualitativeEffects: [
        "Sinais gravados nas pedras da fronteira ardem quando algo errado se aproxima.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "fundar-um-observatorio",
    title: "Fundar um Observatório",
    category: "EXPLORATION",
    durationTurns: 5,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Constrói um observatório para estudo dos astros, auxiliando em previsões e navegação.",
    completionEffects: ce({
      assets: ["Observatório"],
      qualitativeEffects: [
        "De noite, alguém no alto da torre sabe o que o céu vai fazer amanhã.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "pesquisar-um-artefato",
    title: "Pesquisar um Artefato",
    category: "MAGIC",
    durationTurns: 3,
    costs: [w(1)],
    requirements: [],
    description: "Pesquisa a origem, função e riscos de um artefato misterioso em posse da Casa.",
    completionEffects: ce({
      assets: ["Artefato Compreendido"],
      unlocks: ["contratar-a-ordem-dos-tres"],
      qualitativeEffects: ["O objeto deixa de ser enigma e passa a ser responsabilidade."],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: true,
  },
  {
    id: "criar-uma-biblioteca-regional",
    title: "Criar uma Biblioteca Regional",
    category: "EXPLORATION",
    durationTurns: 5,
    costs: [w(2), r(1)],
    requirements: [],
    description: "Funda uma biblioteca regional para preservar conhecimento e desbloquear pesquisas avançadas.",
    completionEffects: ce({
      assets: ["Biblioteca Regional"],
      qualitativeEffects: [
        "Estudiosos de fora atravessam o reino só para ler o que a Casa guarda.",
      ],
    }),
    risks: [],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
  {
    id: "organizar-uma-expedicao-alem-das-fronteiras",
    title: "Organizar uma Expedição Além das Fronteiras",
    category: "EXPLORATION",
    durationTurns: 4,
    costs: [r(2), w(1)],
    requirements: [],
    description: "Organiza uma expedição além das fronteiras conhecidas para explorar territórios e povos.",
    completionEffects: ce({
      assets: ["Rota Além das Fronteiras"],
      unlocks: ["criar-uma-biblioteca-regional"],
      qualitativeEffects: ["O mapa cresce, e com ele cresce a lista do que se ignora."],
    }),
    risks: ["parte da expedição pode não retornar"],
    requiresTargetApproval: false,
    requiresGmApproval: false,
  },
];

export function getTemplate(id: string): ProjectTemplate | undefined {
  return DEFAULT_PROJECT_TEMPLATES.find((t) => t.id === id);
}
